#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/MercuryTechnologies/mercury-go,github.com/stainless-sdks/mercury-go"

REPLACEMENT="${1:-"../mercury-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/MercuryTechnologies/mercury-go="$REPLACEMENT"
go mod tidy -e
